spring.application.name=reprocessamento

logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

xml.path=./revista

#spring.datasource.url=jdbc:postgresql://localhost:5432/reprocessamento
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.main.web-application-type=servlet
